-- MySQL Script generated by MySQL Workbench
-- Kam 03 Okt 2019 08:40:23  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema toko_online
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `toko_online` ;

-- -----------------------------------------------------
-- Schema toko_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toko_online` DEFAULT CHARACTER SET utf8 ;
USE `toko_online` ;

-- -----------------------------------------------------
-- Table `toko_online`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toko_online`.`account` ;

CREATE TABLE IF NOT EXISTS `toko_online`.`account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `is_seller` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toko_online`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toko_online`.`session` ;

CREATE TABLE IF NOT EXISTS `toko_online`.`session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL,
  `key` VARCHAR(128) NOT NULL,
  `creation` FLOAT NOT NULL,
  `expired` FLOAT NOT NULL,
  `is_expired` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `secret_key_UNIQUE` (`key` ASC),
  INDEX `fk_session_account_idx` (`account_id` ASC),
  CONSTRAINT `fk_session_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `toko_online`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toko_online`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toko_online`.`product` ;

CREATE TABLE IF NOT EXISTS `toko_online`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL,
  `nama` VARCHAR(128) NOT NULL,
  `harga` INT NOT NULL,
  `remaining` INT NOT NULL,
  `category` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_product_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `toko_online`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
